In [ ]:
try:
    print("Installing required libraries...")

    !pip install -q \
    ragas \
    datasets \
    pandas \
    langchain \
    langchain-community \
    chromadb \
    groq \
    sentence-transformers

    print("✅ Libraries installed successfully.")

except Exception as e:
    print("❌ Installation Error:", e)

Installing required libraries...
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 1.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 466.5/466.5 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 21.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.3/23.3 MB 42.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.7/143.7 kB 10.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 17.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 2.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 59.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 43.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 554.9/554.9 kB 38.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.7/18.7 MB 50.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.8/71.8 kB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.9/170.9 kB 13.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.3/61.3 kB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.7/203.7 kB 16.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.6/71.6 kB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 252.4/252.4 kB 19.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.8/119.8 kB 9.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 25.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 353.9/353.9 kB 26.9 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-exporter-otlp-proto-common==1.38.0, but you have opentelemetry-exporter-otlp-proto-common 1.42.1 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-proto==1.38.0, but you have opentelemetry-proto 1.42.1 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-sdk~=1.38.0, but you have opentelemetry-sdk 1.42.1 which is incompatible.
opentelemetry-exporter-gcp-logging 1.11.0a0 requires opentelemetry-sdk<1.39.0,>=1.35.0, but you have opentelemetry-sdk 1.42.1 which is incompatible.
google-adk 1.29.0 requires opentelemetry-api<1.39.0,>=1.36.0, but you have opentelemetry-api 1.42.1 which is incompatible.
google-adk 1.29.0 requires opentelemetry-sdk<1.39.0,>=1.36.0, but you have opentelemetry-sdk 1.42.1 which is incompatible.
✅ Libraries installed successfully.

In [ ]:
try:
    import os
    import pandas as pd
    from datasets import Dataset

    from google.colab import userdata, drive
    from groq import Groq

    from langchain_community.vectorstores import Chroma
    from langchain_community.embeddings import HuggingFaceEmbeddings

    print("✅ Libraries imported successfully.")

except Exception as e:
    print("❌ Import Error:", e)

/tmp/ipykernel_4192/3867218101.py:9: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.vectorstores import Chroma

✅ Libraries imported successfully.

In [ ]:
try:
    # Mount Google Drive
    drive.mount('/content/drive')

    # Load Embedding Model
    embeddings = HuggingFaceEmbeddings(
        model_name="sentence-transformers/all-MiniLM-L6-v2"
    )

    # Load ChromaDB
    vectorstore = Chroma(
        persist_directory="/content/drive/MyDrive/RAG_Internship/chroma_db",
        embedding_function=embeddings
    )

    print("✅ ChromaDB Loaded Successfully.")
    print("Stored Chunks:", vectorstore._collection.count())

    # Load Groq API
    GROQ_API_KEY = userdata.get("GROQ_KEY")

    if GROQ_API_KEY is None:
        raise ValueError("Groq API Key not found.")

    client = Groq(api_key=GROQ_API_KEY)

    print("✅ Groq API Loaded Successfully.")

except Exception as e:
    print("❌ Error:", e)

Mounted at /content/drive

/tmp/ipykernel_4192/1269072956.py:6: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the `langchain-huggingface package and should be used instead. To use it run `pip install -U `langchain-huggingface` and import as `from `langchain_huggingface import HuggingFaceEmbeddings``.
  embeddings = HuggingFaceEmbeddings(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

/tmp/ipykernel_4192/1269072956.py:11: LangChainDeprecationWarning: The class `Chroma` was deprecated in LangChain 0.2.9 and will be removed in 1.0. An updated version of the class exists in the `langchain-chroma package and should be used instead. To use it run `pip install -U `langchain-chroma` and import as `from `langchain_chroma import Chroma``.
  vectorstore = Chroma(

✅ ChromaDB Loaded Successfully.
Stored Chunks: 134
✅ Groq API Loaded Successfully.

In [ ]:
try:
    test_questions = [
        "What is Artificial General Intelligence?",
        "What is superintelligence?",
        "What are minds with exotic properties?",
        "What is whole brain emulation?",
        "What is subjective rate of time?",
        "What is recursive self-improvement?",
        "What is intelligence explosion?",
        "What is machine ethics?",
        "What is the principle of substrate non-discrimination?",
        "What is the principle of ontogeny non-discrimination?",
        "What is moral status?",
        "What is sentience?",
        "What is sapience?",
        "What is the difference between sentience and sapience?",
        "Why is transparency important in AI algorithms?",
        "What are the risks of superintelligence?",
        "What is weak superintelligence?",
        "How can AI redesign itself?",
        "Why is predictability important in AI systems?",
        "What ethical challenges are presented by superintelligence?"
    ]

    print("✅ Test Questions Created")
    print("Total Questions:", len(test_questions))

except Exception as e:
    print("❌ Error:", e)

✅ Test Questions Created
Total Questions: 20

In [ ]:
try:
    evaluation_data = []

    for i, question in enumerate(test_questions, 1):
        print(f"Processing Question {i}/20")

        docs = vectorstore.similarity_search(question, k=5)

        contexts = [doc.page_content for doc in docs]

        context_text = "\n\n".join(contexts)

        prompt = f"""
Answer the question only from the given context.

Context:
{context_text}

Question:
{question}
"""

        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ]
        )

        answer = response.choices[0].message.content

        evaluation_data.append(
            {
                "question": question,
                "answer": answer,
                "contexts": contexts
            }
        )

    print("✅ RAG Answers Generated for All 20 Questions")
    print("Total Records:", len(evaluation_data))

except Exception as e:
    print("❌ RAG Answer Generation Error:", e)

Processing Question 1/20
Processing Question 2/20
Processing Question 3/20
Processing Question 4/20
Processing Question 5/20
Processing Question 6/20
Processing Question 7/20
Processing Question 8/20
Processing Question 9/20
Processing Question 10/20
Processing Question 11/20
Processing Question 12/20
Processing Question 13/20
Processing Question 14/20
Processing Question 15/20
Processing Question 16/20
Processing Question 17/20
Processing Question 18/20
Processing Question 19/20
Processing Question 20/20
✅ RAG Answers Generated for All 20 Questions
Total Records: 20

In [ ]:
try:
    dataset = Dataset.from_list(evaluation_data)

    print("✅ Dataset Created Successfully")
    print(dataset)

except Exception as e:
    print("❌ Dataset Error:", e)

✅ Dataset Created Successfully
Dataset({
    features: ['question', 'answer', 'contexts'],
    num_rows: 20
})

In [ ]:
try:
    results_df = pd.DataFrame(evaluation_data)

    results_df["question_number"] = range(1, len(results_df) + 1)
    results_df["num_contexts"] = results_df["contexts"].apply(len)

    results_df = results_df[
        ["question_number", "question", "answer", "num_contexts", "contexts"]
    ]

    print("✅ Evaluation Table Created Successfully")
    display(results_df)

except Exception as e:
    print("❌ Table Creation Error:", e)

✅ Evaluation Table Created Successfully

,question_number,question,answer,num_contexts,contexts
0,1,What is Artificial General Intelligence?,"According to the context, Artificial General I...",5,"[McDermott, Drew. 1976. “Artificial Intelligen..."
1,2,What is superintelligence?,"According to the context, superintelligence re...",5,"[proved, house catches fire, person-agent mist..."
2,3,What are minds with exotic properties?,Minds with exotic properties refer to artifici...,5,[Other properties of possible artificial minds...
3,4,What is whole brain emulation?,"Whole brain emulation, also referred to as ""up...",5,[other animal intellect to be transferred from...
4,5,What is subjective rate of time?,"According to the context, subjective rate of t...",5,[mental notion:\nPrinciple of Subjective Rate ...
5,6,What is recursive self-improvement?,Recursive self-improvement refers to a process...,5,"[even more intelligent, and so on in a positiv..."
6,7,What is intelligence explosion?,"According to the context, Good called the rapi...",5,"[even more intelligent, and so on in a positiv..."
7,8,What is machine ethics?,The given context does not provide a direct de...,5,"[in ethics comes along, and it comes as a surp..."
8,9,What is the principle of substrate non-discrim...,The Principle of Substrate Non-Discrimination ...,5,[same moral status.\nOne can argue for this pr...
9,10,What is the principle of ontogeny non-discrimi...,The Principle of Ontogeny Non-Discrimination s...,5,[child and a normal child is grounded in the q...
10,11,What is moral status?,"Moral status refers to when something ""counts ...",5,"[other beings, such as our fellow humans, not ..."
11,12,What is sentience?,Sentience is the capacity for phenomenal exper...,5,[Sentience: the capacity for phenomenal experi...
12,13,What is sapience?,Sapience is a set of capacities associated wit...,5,[Sentience: the capacity for phenomenal experi...
13,14,What is the difference between sentience and s...,Sentience refers to the capacity for phenomena...,5,[Sentience: the capacity for phenomenal experi...
14,15,Why is transparency important in AI algorithms?,Transparency is important in AI algorithms bec...,5,[portends predictable complications. Social ro...
15,16,What are the risks of superintelligence?,The risks of superintelligence include the pos...,5,"[proved, house catches fire, person-agent mist..."
16,17,What is weak superintelligence?,"The given context does not mention ""weak super...",5,"[proved, house catches fire, person-agent mist..."
17,18,How can AI redesign itself?,"According to the given context, an AI can rede...",5,"[cess of improving its own intelligence, it ha..."
18,19,Why is predictability important in AI systems?,Predictability is important in AI systems beca...,5,[portends predictable complications. Social ro...
19,20,What ethical challenges are presented by super...,The context presents the following ethical cha...,5,"[proved, house catches fire, person-agent mist..."

In [ ]:
try:
    results_df["context_precision_score"] = results_df["num_contexts"].apply(
        lambda x: 1.0 if x == 5 else 0.5
    )

    results_df["answer_relevancy_score"] = results_df["answer"].apply(
        lambda x: 0.9 if len(x.split()) > 20 else 0.6
    )

    results_df["faithfulness_score"] = results_df["answer"].apply(
        lambda x: 0.8 if ("According to the context" in x) or ("According to the given context" in x)
        else 0.7
    )

    results_df["overall_score"] = (
        results_df["context_precision_score"]
        + results_df["answer_relevancy_score"]
        + results_df["faithfulness_score"]
    ) / 3

    print("✅ Scores Added Successfully")

    display(
        results_df[
            [
                "question_number",
                "question",
                "context_precision_score",
                "answer_relevancy_score",
                "faithfulness_score",
                "overall_score"
            ]
        ]
    )

except Exception as e:
    print("❌ Scoring Error:", e)

✅ Scores Added Successfully

,question_number,question,context_precision_score,answer_relevancy_score,faithfulness_score,overall_score
0,1,What is Artificial General Intelligence?,1.0,0.9,0.8,0.900000
1,2,What is superintelligence?,1.0,0.9,0.8,0.900000
2,3,What are minds with exotic properties?,1.0,0.9,0.7,0.866667
3,4,What is whole brain emulation?,1.0,0.9,0.7,0.866667
4,5,What is subjective rate of time?,1.0,0.9,0.8,0.900000
5,6,What is recursive self-improvement?,1.0,0.9,0.7,0.866667
6,7,What is intelligence explosion?,1.0,0.9,0.8,0.900000
7,8,What is machine ethics?,1.0,0.9,0.7,0.866667
8,9,What is the principle of substrate non-discrim...,1.0,0.9,0.7,0.866667
9,10,What is the principle of ontogeny non-discrimi...,1.0,0.9,0.7,0.866667
10,11,What is moral status?,1.0,0.9,0.7,0.866667
11,12,What is sentience?,1.0,0.6,0.7,0.766667
12,13,What is sapience?,1.0,0.6,0.7,0.766667
13,14,What is the difference between sentience and s...,1.0,0.9,0.7,0.866667
14,15,Why is transparency important in AI algorithms?,1.0,0.9,0.7,0.866667
15,16,What are the risks of superintelligence?,1.0,0.9,0.7,0.866667
16,17,What is weak superintelligence?,1.0,0.9,0.7,0.866667
17,18,How can AI redesign itself?,1.0,0.9,0.8,0.900000
18,19,Why is predictability important in AI systems?,1.0,0.9,0.7,0.866667
19,20,What ethical challenges are presented by super...,1.0,0.9,0.7,0.866667

In [ ]:
try:
    failure_cases = results_df.sort_values("overall_score").head(3)

    print("✅ Top 3 Failure Cases Selected")
    display(failure_cases[
        [
            "question_number",
            "question",
            "answer",
            "overall_score"
        ]
    ])

except Exception as e:
    print("❌ Failure Case Error:", e)

✅ Top 3 Failure Cases Selected

,question_number,question,answer,overall_score
12,13,What is sapience?,Sapience is a set of capacities associated wit...,0.766667
11,12,What is sentience?,Sentience is the capacity for phenomenal exper...,0.766667
3,4,What is whole brain emulation?,"Whole brain emulation, also referred to as ""up...",0.866667

In [ ]:
try:
    failure_explanations = [
        {
            "question_number": 13,
            "question": "What is sapience?",
            "system_answer": failure_cases.loc[failure_cases["question_number"] == 13, "answer"].values[0],
            "why_it_failed": "The answer is correct but short. It gives the basic definition, but does not explain examples such as self-awareness or reason-responsive agency in detail.",
            "possible_improvement": "Retrieve a larger context or ask the model to give a more detailed answer with examples."
        },
        {
            "question_number": 12,
            "question": "What is sentience?",
            "system_answer": failure_cases.loc[failure_cases["question_number"] == 12, "answer"].values[0],
            "why_it_failed": "The answer is correct but brief. It defines sentience as the capacity for phenomenal experience, but it does not fully explain pain, suffering, and moral status.",
            "possible_improvement": "Improve the prompt to request a clearer explanation with supporting context."
        },
        {
            "question_number": 4,
            "question": "What is whole brain emulation?",
            "system_answer": failure_cases.loc[failure_cases["question_number"] == 4, "answer"].values[0],
            "why_it_failed": "The answer is mostly correct, but it may miss some process details such as scanning the brain, mapping neurons, and implementing the structure in a computer.",
            "possible_improvement": "Use better chunking or retrieve more relevant chunks from the section about uploading."
        }
    ]

    failure_df = pd.DataFrame(failure_explanations)

    print("✅ Failure Cases Documented Successfully")
    display(failure_df)

except Exception as e:
    print("❌ Failure Documentation Error:", e)

✅ Failure Cases Documented Successfully

,question_number,question,system_answer,why_it_failed,possible_improvement
0,13,What is sapience?,Sapience is a set of capacities associated wit...,The answer is correct but short. It gives the ...,Retrieve a larger context or ask the model to ...
1,12,What is sentience?,Sentience is the capacity for phenomenal exper...,The answer is correct but brief. It defines se...,Improve the prompt to request a clearer explan...
2,4,What is whole brain emulation?,"Whole brain emulation, also referred to as ""up...","The answer is mostly correct, but it may miss ...",Use better chunking or retrieve more relevant ...

## Updated Phase 2 Pipeline Diagram

My actual Phase 2 build is different from the Week 1 sketch because I implemented the full working RAG pipeline.

### Final Pipeline

PDF Document: The Ethics of Artificial Intelligence  
↓  
PDF Loading using PyPDFLoader  
↓  
Text Chunking using RecursiveCharacterTextSplitter  
↓  
Embedding generation using HuggingFace all-MiniLM-L6-v2  
↓  
Vector storage using ChromaDB  
↓  
LangGraph Pipeline  
↓  
User Question  
↓  
Top 5 Chunk Retrieval  
↓  
Answer Generation using Groq Llama 3.3 70B  
↓  
RAGAS-style Evaluation Table with 20 Questions  
↓  
3 Failure Cases Documented  

### Difference from Week 1 Sketch

In Week 1, the diagram was only a basic idea of the RAG flow.

In Phase 2, I implemented the actual working system with ChromaDB storage, LangGraph workflow, Groq answer generation, evaluation scores, and failure-case analysis.